# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20171031_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertausuario',
            name='procentaje_cambio',
            field=models.IntegerField(default=0, help_text='Numero entero', verbose_name='Porcentaje de cambio en la tasa'),
        ),
    ]
