# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20171109_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertausuario',
            name='frecuencia',
            field=models.IntegerField(default=120, help_text='Tiempo en segundos', verbose_name='frecuencia de notificacion de alertas en minutos'),
        ),
        migrations.AlterField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 9, 19, 9, 54, 691977), null=True),
        ),
    ]
