# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_auto_20171117_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 21, 14, 54, 2, 920406), null=True),
        ),
    ]
