# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_auto_20171121_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 21, 14, 56, 28, 8082), null=True),
        ),
    ]
