# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 17:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_auto_20171121_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 12, 17, 16, 19, 38743), null=True),
        ),
    ]
