# Generated by Django 2.0.1 on 2018-04-26 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_auto_20180112_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mencion', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComandoEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_id', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('chat_id', models.IntegerField(default=0)),
                ('comando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comandos', to='bot.Comando')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2018, 4, 26, 12, 23, 55, 980718))),
            ],
            options={
                'ordering': ['fecha'],
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_id', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, default='Sin Descripcion', max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='PersonaContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_buyer_seller', models.CharField(blank=True, max_length=50, null=True)),
                ('puntuacion', models.CharField(choices=[('pos', 'Positivo'), ('neg', 'Negativo'), ('neu', 'Neutral')], default='neu', max_length=15)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='bot.Contrato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bot.User')),
            ],
        ),
        migrations.AlterField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 26, 12, 23, 55, 980195), null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Grupo'),
        ),
    ]
