# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20171030_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertausuario',
            name='periodicidad',
            field=models.DurationField(default=datetime.timedelta(0, 300)),
        ),
    ]
