# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20171030_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertausuario',
            name='ultima_actualizacion',
        ),
    ]
