# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_alertausuario_periodicidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertausuario',
            name='periodicidad',
            field=models.IntegerField(default=300),
        ),
    ]
