# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20171030_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertausuario',
            name='periodicidad',
            field=models.FloatField(default=300.0),
        ),
    ]
