# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20171030_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertausuario',
            name='periodicidad',
        ),
    ]
