# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alertausuario_ultima_actualizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertausuario',
            name='ultima_actualizacion',
        ),
        migrations.AddField(
            model_name='alertausuario',
            name='frecuencia',
            field=models.IntegerField(default=300),
        ),
    ]
