# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20171031_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alertausuario',
            name='frecuencia',
            field=models.IntegerField(default=1200, help_text='Tiempo en segundos', verbose_name='frecuencia de notificacion de alertas en segundos'),
        ),
    ]
