# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20171109_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertausuario',
            name='chat_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 18, 13, 50, 254179)),
        ),
    ]
