# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 20:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_auto_20171117_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 17, 20, 0, 3, 998267), null=True),
        ),
    ]
