# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_auto_20180115_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComandoEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_id', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('chat_id', models.IntegerField(default=0)),
                ('comando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comandos', to='bot.Comando')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_id', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 18, 13, 55, 58, 465968), null=True),
        ),
    ]
