# Generated by Django 2.0.1 on 2018-01-24 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0032_auto_20180124_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 24, 13, 45, 22, 807931), null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 13, 45, 22, 808494)),
        ),
    ]
