# Generated by Django 2.0.1 on 2018-01-24 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0037_auto_20180124_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 24, 15, 18, 15, 751525), null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 15, 18, 15, 753116)),
        ),
    ]
