# Generated by Django 2.0.1 on 2018-01-24 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0042_auto_20180124_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 24, 16, 11, 1, 14163), null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 16, 11, 1, 15276)),
        ),
    ]
