# Generated by Django 2.0.1 on 2018-06-12 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0045_auto_20180125_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mencion', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='alertausuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 12, 11, 51, 16, 519011, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 11, 51, 16, 520113)),
        ),
    ]
